# # apiVersion: extensions/v1beta1
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: puzzle
#   labels:
#     app: puzzle
# spec:
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: puzzle
#         tier: puzzle
#     spec:
#       containers:
#       - image: 127.0.0.1:30400/puzzle:93faf8a
#         name: puzzle
#         imagePullPolicy: Always
#         lifecycle:
#           postStart:
#             exec:
#               command: ["/up.sh"]
#           preStop:
#             exec:
#               command: ["/down.sh"]        
#         ports:
#         - containerPort: 3000
#           name: puzzle

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: puzzle
#   labels:
#     app: puzzle
# spec:
#   ports:
#     - port: 3000
#       targetPort: 3000
#   selector:
#     app: puzzle
#     tier: puzzle
#   type: NodePort
# ---
# # apiVersion: extensions/v1beta1
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongo
#   labels:
#     app: mongo
# spec:
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: mongo
#         tier: mongo
#     spec:
#       containers:
#       - image: mongo:3.7
#         name: mongo
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 27017
#           name: mongo
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
#   labels:
#     app: mongo
# spec:
#   ports:
#     - port: 27017
#       targetPort: 27017
#   selector:
#     app: mongo
#     tier: mongo
#   type: NodePort
# ---
# # apiVersion: extensions/v1beta1
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#  name: puzzle
# spec:
#   backend:
#     serviceName: puzzle
#     servicePort: 3000
#   rules:
#   - host: puzzle.192.168.99.100.xip.io
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: puzzle
#           servicePort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzle
  labels:
    app: puzzle
spec:
  selector:
    matchLabels:
      app: puzzle
      tier: puzzle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: puzzle
        tier: puzzle
    spec:
      restartPolicy: Always
      containers:
      - name: puzzle
        image: 127.0.0.1:30400/puzzle:93faf8a
        imagePullPolicy: Always
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/up.sh"]
        #   preStop:
        #     exec:
        #       command: ["/down.sh"]
        ports:
        - containerPort: 3000
          name: puzzle
---
apiVersion: v1
kind: Service
metadata:
  name: puzzle
  labels:
    app: puzzle
spec:
  type: NodePort
  ports:
  - name: puzzle
    port: 3000
    targetPort: 3000
    nodePort: 31120
  selector:
    app: puzzle
    tier: puzzle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        tier: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: mongo
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
#   labels:
#     app: mongo
# spec:
#   type: NodePort
#   ports:
#   - name: mongo
#     port: 27017
#     targetPort: 27017
#   selector:
#     app: mongo
#     tier: mongo
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: puzzle
# spec:
#   rules:
#   # - host: puzzle.192.168.99.100.xip.io
#   - host: puzzle.10.96.0.1.xip.io
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: puzzle
#             port:
#               number: 3000

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: puzzle
# spec:
#   rules:
#   - host: puzzle.10.96.0.1.xip.io
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: puzzle
#             port:
#               number: 3000
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
    tier: mongo
  # type: NodePort
  type: LoadBalancer

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: puzzle
# spec:
#   rules:
#   # - host: puzzle.192.168.99.100.xip.io
#   - host: puzzle.192.168.65.4.xip.io
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: puzzle
#             port:
#               number: 3000
