apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-deployment-creator
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*" ]
