apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubectl-api-role
subjects:
- kind: ServiceAccount
  name: kubectl-api-sa
  namespace: default
