apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-scale-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitor-scale-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
