apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-scale-role
rules:
- apiGroups: [""]
  resources: ["services", "deployments"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
